# Generated by Django 5.1.3 on 2024-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_date_events_start_date_events_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
